-- Mostre o seu / Links visíveis → tabela CardReadmeShares
-- Roda no Postgres (pgAdmin ou psql) na base buildxpdb.

CREATE TABLE IF NOT EXISTS "CardReadmeShares" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CardId" integer NULL REFERENCES "SkillCards" ("Id") ON DELETE CASCADE,
    "Nome" character varying(80) NOT NULL,
    "GithubLink" character varying(500) NOT NULL,
    "OwnerToken" uuid NOT NULL DEFAULT gen_random_uuid(),
    "CriadoEm" timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE "CardReadmeShares" ALTER COLUMN "CardId" DROP NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'CardReadmeShares' AND column_name = 'OwnerToken'
    ) THEN
        ALTER TABLE "CardReadmeShares"
            ADD COLUMN "OwnerToken" uuid NOT NULL DEFAULT gen_random_uuid();
    END IF;
END $$;

-- Ver o que está visível hoje
SELECT "Id", "Nome", "GithubLink", "CriadoEm"
FROM "CardReadmeShares"
ORDER BY "CriadoEm" DESC, "Id" DESC;

-- Tirar duplicados do mesmo GitHub (fica o mais recente)
DELETE FROM "CardReadmeShares" a
USING "CardReadmeShares" b
WHERE a."GithubLink" = b."GithubLink"
  AND a."Id" < b."Id";

-- Excluir um link específico (troca o Id)
-- DELETE FROM "CardReadmeShares" WHERE "Id" = 1;

-- Limpar todos os testes
-- DELETE FROM "CardReadmeShares";
